name: Quarkiverse Create Initial Comment on PR

on:
  pull_request_target:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  comment:
    name: Create PR comment
    uses: quarkiverse/.github/.github/workflows/perform-post-comment.yml@main
