name: Quarkiverse Perform post Test Report(s) to PR

on:
  # Called in the pr report workflow
  workflow_call:
    inputs:
      report-config-file:
        description: |
          relative path to file report-config.yml
        default: .github/report-config.yml
        type: string

permissions:
  checks: write
  pull-requests: write

jobs:
  load:
    name: Load config and override initial comment
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.load.outputs.config }}
      pr-number: ${{ steps.set-pr-number.outputs.pr-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Load report config
        id: load
        run: |
          if [[ -f ${CONFIG_FILE} ]] && [[ $(yq '.reports | length > 0' "${CONFIG_FILE}") == "true" ]]
          then
            config=$(yq \
              --indent 0 \
              --output-format json \
              '.include = .reports | del(.reports)' "${CONFIG_FILE}")
          fi
          echo "config=${config}" >> ${GITHUB_OUTPUT}
        env:
          CONFIG_FILE: ${{ inputs.report-config-file }}
      - name: Download PR number
        if: ${{ steps.load.outputs.config != '' }}
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ github.token }}
          name: pr-number
          run-id: ${{ env.RUN_ID }}
        env:
          RUN_ID: ${{ github.event.workflow_run.id }}
      - name: Set PR number
        id: set-pr-number
        if: ${{ steps.load.outputs.config != '' }}
        run: |
          echo "pr-number=$(cat pr-number.txt)" >> "${GITHUB_OUTPUT}"
      - name: Override initial comment
        if: ${{ steps.load.outputs.config != '' }}
        uses: turing85/publish-report@v2
        with:
          override-comment: true
          comment-message-override: |
            ## 🚦Reports for run [#${{ env.RUN_NUMBER }}](${{ env.GH_SERVER }}/${{ env.GH_REPO }}/actions/runs/${{ env.RUN_ID }})🚦
            Reports will be posted here as they get available.
          comment-message-pr-number: ${{ env.PR_NUMBER }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_SERVER: ${{ github.server_url }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          RUN_NUMBER: ${{ github.event.workflow_run.run_number }}
          PR_NUMBER: ${{ steps.set-pr-number.outputs.pr-number }}

  post-reports:
    name: Add report ${{ matrix.name }}
    runs-on: ubuntu-latest
    needs:
      - load
    if: ${{ needs.load.outputs.config != '' }}
    strategy:
      matrix: ${{ fromJson(needs.load.outputs.config) }}
      max-parallel: 1
    steps:
      - name: Post report
        if: ${{ always() }}
        uses: turing85/publish-report@v2
        with:
          checkout: true
          comment-message-pr-number: ${{ env.PR_NUMBER }}
          download-artifact-pattern: ${{ env.TEST_ARTIFACT_PATTERN }}
          download-artifact-merge-multiple: true
          download-artifact-run-id: ${{ env.RUN_ID }}
          report-name: ${{ env.TEST_REPORT_NAME }}
          report-path: ${{ env.TEST_REPORT_PATH }}
        env:
          PR_NUMBER: ${{ needs.load.outputs.pr-number }}
          RUN_ID: ${{ github.event.workflow_run.id }}
          TEST_ARTIFACT_PATTERN: ${{ matrix.artifact-pattern }}
          TEST_REPORT_NAME: ${{ matrix.name }}
          TEST_REPORT_PATH: ${{ matrix.path }}
